### PR TITLE
Only notify developers on build failure; formatting

### PR DESCRIPTION
**Pull request by danielbachhuber**

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@goldenapples Are tests passing locally for you?

**Comment by goldenapples** [comment]
I'm getting this phpcs warning:

﻿```
FILE: .../wp-content/plugins/image-shortcake/tests/test-img-shortcode.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 86 | WARNING | file_get_contents is highly discouraged, please use
    |         | wpcom_vip_file_get_contents() instead.
----------------------------------------------------------------------
```
but otherwise all tests are passing.

It doesn't feel right to make the plugin test work only in VIP environment. I'll change the ruleset to remove some of the VIP-specific rules.

**Comment by goldenapples** [comment]
Oh. This branch doesn't have the right require line to load the plugin:

https://github.com/fusioneng/image-shortcake/blob/send-to-editor/tests/bootstrap.php#L12

Its fixed in my other branch.

**Comment by danielbachhuber** [comment]
This was addressed in #19

**Pull request closed without merging**
